### ISSUE TITLE
Remove S3 `lifecycle` blocks after we move to version 4.x of Terraform AWS provider

### ISSUE THREAD

**Issue by dav3r** [cisagov/publish-egress-ip-terraform#5]
# 💡 Summary #

Remove the `lifecycle` blocks for both S3 buckets in this repository after we move ourselves to version 4.x of the Terraform AWS provider.

## Motivation and context ##

These `lifecycle` blocks (found [here](https://github.com/cisagov/publish-egress-ip-terraform/blob/c7a2e927dafb4a8c91e39cd5ad93159f2485a21c/s3.tf#L11-L15) and [here](https://github.com/cisagov/publish-egress-ip-terraform/blob/c7a2e927dafb4a8c91e39cd5ad93159f2485a21c/cloudfront.tf#L31-L35)) are necessary to prevent Terraform from "flip-flopping" the encryption (removing it and adding it) on subsequent applies.  For more info, see https://github.com/hashicorp/terraform-provider-aws/issues/23758.

## Implementation notes ##

None

## Acceptance criteria ##

How do we know when this work is done?

- [x] Both S3 `lifecycle` blocks have been removed
- [x] Consecutive Terraform `apply` commands do not cause the bucket encryption to be disabled/enabled.

**Comment by Alexdelarose** [comment]
Any idea how to prioritize this?
